#!/bin/bash

apt-get update
apt-get install nginx php8.3-pgsql php-apcu php8.3 php8.3-fpm php8.3-mysql php8.3-gd php8.3-common php8.3-curl php8.3-intl php8.3-gmp php8.3-xml php-dev php-pear unzip git -y
sleep 10
wget https://github.com/shlinkio/shlink/releases/download/v4.4.3/shlink4.4.3_php8.3_dist.zip
unzip shlink4.4.3_php8.3_dist.zip
mv shlink4.4.3_php8.3_dist shlink_back
mv shlink_back /var/www/

chown -R www-data:www-data /var/www/shlink_back/
chmod -R 755 /var/www/shlink_back/

# Кидаем config для shlink 
echo "<?php

/* Shlink config generated by shlink-installer */

return array (
  'RUNTIME' => 'regular',
  'MEMORY_LIMIT' => '512M',
  'DB_DRIVER' => 'postgres',
  'DB_NAME' => 'pdo_pgsql',
  'DB_HOST' => '192.168.1.102',
  'DB_PORT' => '5432',
  'DB_USER' => 'pdo_pgsql',
  'DB_PASSWORD' => 'password',
  'DB_USE_ENCRYPTION' => false,
  'DEFAULT_DOMAIN' => '192.168.1.103',
  'IS_HTTPS_ENABLED' => false,
  'DEFAULT_SHORT_CODES_LENGTH' => 5,
  'AUTO_RESOLVE_TITLES' => true,
  'REDIRECT_EXTRA_PATH_MODE' => 'default',
  'MULTI_SEGMENT_SLUGS_ENABLED' => false, 
  'SHORT_URL_TRAILING_SLASH' => false,
  'SHORT_URL_MODE' => 'strict',
  'GEOLITE_LICENSE_KEY' => NULL,
  'REDIRECT_STATUS_CODE' => 302,
  'REDIRECT_CACHE_LIFETIME' => 30,
  'DISABLE_TRACKING' => false,
  'TRACK_ORPHAN_VISITS' => true,
  'DISABLE_TRACK_PARAM' => NULL,
  'DISABLE_TRACKING_FROM' => NULL,
  'DISABLE_IP_TRACKING' => false,
  'ANONYMIZE_REMOTE_ADDR' => true,
  'DISABLE_UA_TRACKING' => false,
  'DISABLE_REFERRER_TRACKING' => false,
  'DEFAULT_BASE_URL_REDIRECT' => NULL,
  'DEFAULT_INVALID_SHORT_URL_REDIRECT' => NULL,
  'DEFAULT_REGULAR_404_REDIRECT' => NULL,
  'DEFAULT_QR_CODE_SIZE' => 300,
  'DEFAULT_QR_CODE_MARGIN' => 0,
  'DEFAULT_QR_CODE_FORMAT' => 'png',
  'DEFAULT_QR_CODE_ERROR_CORRECTION' => 'l',
  'DEFAULT_QR_CODE_ROUND_BLOCK_SIZE' => true,
  'DEFAULT_QR_CODE_COLOR' => '#000000',
  'DEFAULT_QR_CODE_BG_COLOR' => '#FFFFFF',
  'DEFAULT_QR_CODE_LOGO_URL' => NULL,
  'QR_CODE_FOR_DISABLED_SHORT_URLS' => true,
  'ROBOTS_ALLOW_ALL_SHORT_URLS' => false,
  'ROBOTS_USER_AGENTS' => NULL,
  'DELETE_SHORT_URL_THRESHOLD' => NULL,
  'BASE_PATH' => '/shlink',
  'TIMEZONE' => NULL,
  'CACHE_NAMESPACE' => 'Shlink',
  'REDIS_SERVERS' => NULL,
  'MATOMO_ENABLED' => false,
);" > /var/www/shlink_back/config/params/generated_config.php 

echo "server {
   listen 81;
#   server_name shlink.example.com;

   root /var/www/shlink_back/public;
   error_log /var/log/nginx/shlink.error;
   access_log /var/log/nginx/shlink.access;

   index index.php index.html index.htm index.nginx-debian.html;

   location /shlink {
     # try to serve file directly, fallback to app.php
     try_files \$uri /index.php\$is_args\$args;
   }

   # redirect some entire folders
     rewrite ^/(vendor|translations|build)/.* /index.php break;

   location ~ \.php$ {
     fastcgi_split_path_info ^(.+\.php)(/.+)$;
     fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
     fastcgi_index index.php;
     fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
     include fastcgi_params;
   }
}" > /etc/nginx/sites-available/shlink_back.conf
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/shlink_back.conf /etc/nginx/sites-enabled/

sudo -u www-data sh -c "cd /var/www/shlink_back && php8.3 vendor/bin/shlink-installer init"
sudo -u www-data sh -c "cd /var/www/shlink_back && php8.3 bin/cli short-url:list"
sudo -u www-data sh -c "cd /var/www/shlink_back && php8.3 bin/cli api-key:list"

systemctl restart nginx